name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: stable

      - name: Build
        run: |
          cd cmd
          go build -ldflags "-s -w" -o ../sc-linux-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o ../sc-darwin-arm64
          GOOS=windows go build -ldflags "-s -w" -o ../sc-win-amd64.exe

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: sc*
